// containers
// containers: application
export const CONTAINER_APPLICATION_ENABLE_BUSY_FLAG: string = "CONTAINER_APPLICATION_ENABLE_BUSY_FLAG";
export const CONTAINER_APPLICATION_DISABLE_BUSY_FLAG: string = "CONTAINER_APPLICATION_DISABLE_BUSY_FLAG";
// containers: collapsableSidebar
export const CONTAINER_COLLAPSABLESIDEBAR_TOGGLE: string = "CONTAINER_COLLAPSABLESIDEBAR_TOGGLE";


